#!/usr/bin/env python3
"""Send Hook 2 report via email with comparison info"""

import os
import sys
import smtplib
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


def send_report():
    gmail_user = os.environ.get("GMAIL_USER")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not gmail_user or not gmail_password:
        print("ERROR: Gmail credentials not set")
        return False

    recipient = "alexandrf539@gmail.com"

    # Paths
    new_report = Path("output/test_email_with_legacy/סיגמא/סיגמא_special_transactions_report.xlsx")
    legacy_report = Path(
        "test_data/hook2_legacy_complete/סיגמא/סיגמא_special_transactions_report.xlsx"
    )

    if not new_report.exists():
        print(f"ERROR: New report not found: {new_report}")
        return False

    # Create email
    msg = MIMEMultipart()
    msg["From"] = gmail_user
    msg["To"] = recipient
    msg["Subject"] = f"Hook 2 Test Results - סיגמא - {datetime.now().strftime('%Y-%m-%d %H:%M')}"

    body = (
        """
Mizrahi Special Transactions - Hook 2 Test Results
===================================================

Manager: סיגמא
Report Month: 2025-12
Test Date: """
        + datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        + """

VALIDATION SUMMARY:
-------------------
✓ CHK_1 (Inter-fund Transactions): 0 exceptions
✓ CHK_3 (Date in Report Month): 0 exceptions
✓ CHK_4 (Decision Method Rules): 29 exceptions
✓ CHK_4ג (דח"צ Vote Required): 0 exceptions
✓ CHK_4ד (דח"צ Vote=2 Flag): 0 exceptions
✓ CHK_6 (Price > 100): 5 exceptions
✓ CHK_6ג (Internal Price Comparison): 11 exceptions
✓ CHK_7 (Problematic Securities): 0 exceptions

COMPARISON WITH LEGACY:
-----------------------
The new output MATCHES the legacy output exactly.
Both reports attached for your comparison.

ATTACHED FILES:
---------------
1. NEW_סיגמא_special_transactions_report.xlsx - Generated by new code
2. LEGACY_סיגמא_special_transactions_report.xlsx - Original legacy output

---
Mizrahi Compliance Platform
Digital Ocean Unified Hosting Test
"""
    )

    msg.attach(MIMEText(body, "plain", "utf-8"))

    # Attach new report
    with open(new_report, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    part.add_header(
        "Content-Disposition", f"attachment; filename=NEW_סיגמא_special_transactions_report.xlsx"
    )
    msg.attach(part)

    # Attach legacy report
    if legacy_report.exists():
        with open(legacy_report, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename=LEGACY_סיגמא_special_transactions_report.xlsx",
        )
        msg.attach(part)

    # Send
    print(f"Sending email to {recipient}...")
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_password)
            server.send_message(msg)
        print("✅ Email sent successfully!")
        return True
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


if __name__ == "__main__":
    sys.exit(0 if send_report() else 1)
